# Generated by Django 2.1.7 on 2019-04-23 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KjzdUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('nick', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True, unique=True)),
                ('tel', models.CharField(blank=True, max_length=64, null=True, unique=True)),
            ],
            options={
                'db_table': 'pre_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('name', models.CharField(blank=True, error_messages={'unique': 'A user with that email already exists.'}, max_length=150, null=True, unique=True, verbose_name='name')),
                ('phone', models.CharField(blank=True, error_messages={'unique': 'A user with that telephone already exists.'}, max_length=64, null=True, unique=True, verbose_name='telephone number')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('kjzd_user_id', models.IntegerField(null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
