# Generated by Django 2.1.7 on 2019-05-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190430_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='name',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that email already exists.'}, max_length=150, null=True, verbose_name='name'),
        ),
    ]
